import React from 'react';
import { Link } from 'react-router-dom';
import { PublicNav } from '../components/PublicNav';
import { PublicFooter } from '../components/PublicFooter';
import { useAuth } from '../context/AuthContext';

export const IntegrationsPage = () => {
  const { isAuthenticated } = useAuth();

  const integrations = [
    {
      title: 'GitHub & Pull Requests',
      category: 'SOURCE CONTROL & CI/CD',
      description: 'Native bidirectional GitHub integration. OmniSight listens to repository webhooks, clones target codebases, creates hotfix branches, and opens ready-to-merge Pull Requests.',
      tags: ['Pull Requests', 'Branch Management', 'Commit SHAs'],
    },
    {
      title: 'Vercel Deployments',
      category: 'CLOUD HOSTING',
      description: 'Audit preview and production deployments generated by Vercel. OmniSight captures full visual snapshots as soon as a build deployment completes.',
      tags: ['Preview URLs', 'Production Audits', 'Edge Speed'],
    },
    {
      title: 'Render Cloud Services',
      category: 'CONTAINER INFRASTRUCTURE',
      description: 'Containerized microservice architecture deployed on Render with automated cold-start recovery and background task orchestration.',
      tags: ['FastAPI Gateway', 'Dockerized Engine', 'Express Backend'],
    },
    {
      title: 'Playwright Browser Cluster',
      category: 'BROWSER AUTOMATION',
      description: 'Headless Chromium browser instances running concurrently to capture mobile, tablet, and desktop responsive viewports under realistic network conditions.',
      tags: ['Multi-Viewport', 'Chromium Engine', 'Zero Headless Glitches'],
    },
    {
      title: 'Tailwind CSS & Modern Frameworks',
      category: 'FRONTEND STACK',
      description: 'Tailored for React, Vite, Next.js, and Tailwind CSS. The self-healing engine parses utility classes and modifies styling attributes with surgical precision.',
      tags: ['Tailwind AST', 'React JSX', 'Responsive Utilities'],
    },
    {
      title: 'Google Gemini & Groq Vision',
      category: 'MULTIMODAL AI',
      description: 'State-of-the-art vision models analyzing UI hierarchy, detecting subtle clipping, bad contrast ratios, and element overlapping.',
      tags: ['Gemini 2.5 Flash', 'Llama 3.2 Vision', 'VLM Heuristics'],
    },
  ];

  return (
    <div className="min-h-screen flex flex-col bg-[#FAFAF8] text-[#1A1A1A] font-sans antialiased selection:bg-[#016464] selection:text-white">
      <PublicNav />

      {/* Hero Header */}
      <section className="pt-16 pb-12 px-6 sm:px-8 text-center max-w-5xl mx-auto">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-teal-50 text-[#016464] text-xs font-bold uppercase tracking-wider mb-4 border border-teal-200/60">
          <span>ECOSYSTEM & INTEGRATIONS</span>
        </div>
        <h1 className="text-4xl sm:text-5xl font-black text-[#1A1A1A] tracking-tight leading-tight">
          Seamlessly integrates with your entire stack.
        </h1>
        <p className="mt-4 text-base sm:text-lg text-slate-600 max-w-2xl mx-auto font-medium leading-relaxed">
          Plug OmniSight into your existing CI/CD pipelines, hosting providers, and frontend repositories.
        </p>
      </section>

      {/* Integrations Grid */}
      <section className="pb-24 px-6 sm:px-8 max-w-6xl mx-auto w-full space-y-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {integrations.map((item) => (
            <div
              key={item.title}
              className="bg-white rounded-3xl p-6 border border-[#E8E6E1] shadow-sm hover:shadow-md transition flex flex-col justify-between"
            >
              <div>
                <p className="text-[10px] font-bold text-[#016464] uppercase tracking-wider mb-2">
                  {item.category}
                </p>
                <h3 className="text-xl font-black text-[#1A1A1A] tracking-tight mb-2.5">
                  {item.title}
                </h3>
                <p className="text-xs text-slate-600 font-medium leading-relaxed mb-6">
                  {item.description}
                </p>
              </div>

              <div className="pt-3 border-t border-slate-100 flex flex-wrap gap-1.5">
                {item.tags.map((tag) => (
                  <span
                    key={tag}
                    className="px-2 py-0.5 rounded-md bg-slate-100 text-slate-600 text-[10px] font-semibold"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Bottom CTA Banner */}
        <div className="bg-[#016464] text-white rounded-3xl p-8 sm:p-12 text-center relative overflow-hidden shadow-lg">
          <div className="relative z-10 max-w-2xl mx-auto">
            <h2 className="text-2xl sm:text-3xl font-black tracking-tight">
              Connect your repository today.
            </h2>
            <p className="mt-3 text-sm sm:text-base text-teal-100 font-medium leading-relaxed">
              Launch your first automated visual audit in under 60 seconds.
            </p>
            <div className="mt-6 flex justify-center">
              <Link
                to={isAuthenticated ? '/app' : '/login'}
                className="px-6 py-3 bg-white hover:bg-slate-50 text-[#016464] font-bold text-sm rounded-xl shadow transition"
              >
                {isAuthenticated ? 'Open Dashboard' : 'Get Started Now'}
              </Link>
            </div>
          </div>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
};
